### ISSUE TITLE
Few minor suggestions

### ISSUE THREAD

**Issue by Christilut** [Richard87/releaser#12]
Github link on the releaser website (this repo is hard to find)

Some minor SEO efforts (releaser is impossible to find in google). I have to go into my mail and find an old releaser email to go to your website..

**Comment by AlexWayfer** [comment]
Faced the same difficulties recently!

**Comment by Richard87** [comment]
Hi, yeah, I agree, unfortunatley I can't do very much about it except "linkbacks", also a little more content on the page about what it does might help...

In other words, I will write some more "about" on releaser, but I need your help to spread the word ;)

Richard

**Comment by Richard87** [comment]
added some github keywords and a ribbon, hope that helps a little bit...
