### ISSUE TITLE
Production keys

### ISSUE THREAD

**Issue by AlexWayfer** [Richard87/releaser#15]
Is it safe to show everyone your production keys?

https://github.com/Richard87/releaser/commit/976d27f59a87e3a5e7f860a6900fcf11d1fe80d5

**Comment by Richard87** [comment]
Yes, they are bound to my domain name, and the way firebase is working...
look at it as a public key :)

lør. 27. mai 2017 kl. 12:41 skrev Alexander Popov <notifications@github.com

**Comment by AlexWayfer** [comment]
Okay, as you say.
