### ISSUE TITLE
Logged is as null

### ISSUE THREAD

**Issue by mikhail-softgrad** [Richard87/releaser#18]
Hello
I always got follow message in the bottom page

![image](https://user-images.githubusercontent.com/29663202/27598576-9a030dd4-5b6e-11e7-9ab8-dd3d29d0b917.png)

Maybe is it bug?

**Comment by msteer** [comment]
I think this might be because you do not have a name set in your GitHub profile.

**Comment by Richard87** [comment]
Yup, that's exactly the problem.

**Comment by AlexWayfer** [comment]
> Yup, that's exactly the problem.

Maybe `Releaser` should display nickname, if profile name is null? Why did you close the issue?

**Comment by Richard87** [comment]
Yeah, we could update it to show the email if displayName is null

**Comment by AlexWayfer** [comment]
> Yeah, we could update it to show the email if displayName is null

Um, why? For example, you have:
*   Profile name: __Richard Hagen__
*   Nickname: __Richard87__
*   Email: _undefined_

We could show __nickname__ (it's required for user) if __profile name__ (not required) is empty, not __email__ (not required).

**Comment by Richard87** [comment]
Hi, we don't have Nickname, we always have email, but sometimes
displayName...

Richard

tor. 29. jun. 2017 kl. 16:41 skrev Alexander Popov <notifications@github.com

**Comment by AlexWayfer** [comment]
@Richard87 So, and what is your email?

![image](https://user-images.githubusercontent.com/6510020/27694417-afe5768c-5cf4-11e7-8d53-75ec15cb441f.png)

**Comment by Richard87** [comment]
To specify, from Firebase Authentication, we just get displayName (in this
example, "Richard Hagen") and email :)

tor. 29. jun. 2017 kl. 16:59 skrev Alexander Popov <notifications@github.com

**Comment by AlexWayfer** [comment]
@Richard87 Oh, okay, thank you.

**Comment by Richard87** [comment]
No problem!

tor. 29. jun. 2017 kl. 18:31 skrev Alexander Popov <notifications@github.com

**Comment by Richard87** [comment]
@AlexWayfer Could you test that it works as expected now?

**Comment by AlexWayfer** [comment]
> @AlexWayfer Could you test that it works as expected now?

[Production](https://releaser.richardhagen.no/)? Still `null` :disappointed:

**Comment by Richard87** [comment]
ahh, thanks, I forgot to push deploy :O

søn. 6. aug. 2017 kl. 20:52 skrev Alexander Popov <notifications@github.com

**Comment by Richard87** [comment]
@AlexWayfer  Just pushed new version, could you try again? Sorry for the inconvenience! I appreciate your help :)

**Comment by AlexWayfer** [comment]
Sure, no problem!

I checked: now the email is displayed :tada: 

You can close this issue :)

**Comment by Richard87** [comment]
Thanks man!
