### ISSUE TITLE
Pale Moon browser compatibility

### ISSUE THREAD

**Issue by Gittyperson** [Richard87/releaser#2]
Thanks for your helpful tool! Your [website](https://releaser.richardhagen.no/) seems to adopt user agent sniffing and thus it does not work with the Pale Moon browser (login window pop-up does not appear).

Problem goes away if the browser's "Firefox compatibility mode" is enabled (it just changes its user agent string to a more Firefox-compatible one) but hopefully the website can be made to work natively (I assume this affects other browsers, too). Examples:

**Pale Moon 26 strings (current version)**

Native (Releaser does not work):
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:2.2) Gecko/20100101 Goanna/20160923 PaleMoon/26.5.0

Firefox mode (works):
Mozilla/5.0` (Windows NT 10.0; WOW64; rv:38.9) Gecko/20100101 Goanna/2.2 Firefox/38.9 PaleMoon/26.5.0

**Pale Moon 27** (new version, currently in beta)

Native (does not work):
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:3.0) Goanna/20161025 PaleMoon/27.0.0b3

Gecko mode (does not work):
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:3.0) Gecko/20100101 Goanna/20161025 PaleMoon/27.0.0b3

Firefox mode (works):
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.9) Gecko/20100101 Goanna/3.0 Firefox/45.9 PaleMoon/27.0.0b3

**Comment by Richard87** [comment]
Hi, thanks for your interrest in my app!

Unfortunatly the bug you are reffering to is a problem in Angularfire2 or Firebase, and have to be fixed there.
