### ISSUE TITLE
Small tweak for the css

### ISSUE THREAD

**Issue by MrDemocracy** [Richard87/releaser#23]
Could you please add this line to the css?
```css
md-sidenav-container {
    height: 100%;
}
```
The page looks a bit chopped up the way it is now:
<img width="1280" src="https://user-images.githubusercontent.com/23060864/31352358-ca29fbdc-ad2e-11e7-96cf-e0d5bf9cc798.png">

Here's an image of how it would look if you made this change:
<img width="1280" src="https://user-images.githubusercontent.com/23060864/31352428-08024afe-ad2f-11e7-9ec7-a0c63b42b72e.png">

**Comment by AlexWayfer** [comment]
@MrDemocracy You can try to make PR :wink:

**Comment by AlexWayfer** [comment]
I think this issue can be closed (@MrDemocracy, you can use [keywords](https://help.github.com/articles/closing-issues-using-keywords/) for this in the future, [example](https://github.com/blog/1506-closing-issues-via-pull-requests)).

**Comment by Richard87** [comment]
Thanks for this @MrDemocracy ! And thanks for the tip @AlexWayfer !
