### ISSUE TITLE
Firefox: "The popup has been closed by the user before finalizing the operation."

### ISSUE THREAD

**Issue by FelixSchwarz** [Richard87/releaser#27]
I'm using Firefox 57 (beta) on Linux. When I click "Login or Signup ..." I see the popup window. This window closes itself after I authorized the data access.

However I'm not logged in afterwards.

In the JS console I see an error:

    code: "auth/popup-closed-by-user"
    message: "The popup has been closed by the user before finalizing the operation."

**Comment by AlexWayfer** [comment]
Everything works on Firefox 56 (stable), Linux, GitHub account with 2FA. Object with keys in JS console.

**Comment by FelixSchwarz** [comment]
Thank you very much for your quick response. Not sure what this means for me: Just wait until FF 57 is stable? Maybe it is a FF bug which might get fixed until the release? Or do you like me to provide more information?

**Comment by FelixSchwarz** [comment]
actually now it works for me as well... Strange. Tried it several times before.

Well I guess it is impossible to find out why this happened so I'm just closing this ticket.

**Comment by AlexWayfer** [comment]
I've installed Firefox Beta 57, works as well.
