### ISSUE TITLE
releaser does not find any releases (e.g. rspamd, radicale)

### ISSUE THREAD

**Issue by FelixSchwarz** [Richard87/releaser#28]
I added links to https://github.com/vstakhov/rspamd and https://github.com/Kozea/Radicale but the web page tells me "No releases" even though both projects saw quite a few releases in the past.

**Comment by AlexWayfer** [comment]
Hello!

Just wait up to 30 minutes: https://github.com/Richard87/releaser/issues/5#issuecomment-260110480

**Comment by FelixSchwarz** [comment]
that did the trick of course :-)
