### ISSUE TITLE
Can you add a license to this project please?

### ISSUE THREAD

**Issue by mdwragg** [Richard87/releaser#4]
Hi,

Thanks for the great project! It looks awesome and really useful!

Just so I know what I'm allowed to do with the project, do you mind adding a license to it? An OSS license would be gladly received too :-)

Thanks again for publishing this.

Regards,
Martin.

**Comment by Richard87** [comment]
Hi! I'll upload a MIT License when I get to my computer..  Let me know if
you make anything cool out of it!

Richard

Den lør. 12. nov. 2016, 03:34 skrev Martin Wragg notifications@github.com:

**Comment by mdwragg** [comment]
Thank you so much! I really appreciate you taking time to add this clarification. Thanks :-)
