### ISSUE TITLE
Does not get the last release

### ISSUE THREAD

**Issue by aruhier** [Richard87/releaser#6]
Hello,
I added [netbox](https://github.com/digitalocean/netbox) in the watch list, but I did not get any notification for the 2 last releases, as netbox in Releaser is frozen in the 1.7.1 version.

Thanks!

**Comment by Richard87** [comment]
Thanks for reporting in! I'll look at it ASAP

Den ons. 21. des. 2016, 01:28 skrev Anthony Ruhier <notifications@github.com

**Comment by aruhier** [comment]
Many thanks!
