### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by AlexWayfer** [Richard87/releaser#7]
Hello!

I can't find https://github.com/odeke-em/drive, by full URL, or just project name, or author name + project name, or parts of this.

It will be fine if `releaser` will find repo in ~100% of cases by full URL.

**Comment by Richard87** [comment]
Hi,  I don't have much time for the moment to work on this,  but I would
love a pull request ☺️

Den fre. 3. feb. 2017, 22:55 skrev Alexander Popov <notifications@github.com

**Comment by Richard87** [comment]
Also, I'm using a simple query like this:

    `https://api.github.com/search/repositories?q=${terms}&sort=stars`

So if the search doesn't work, I believe it is a problem with GitHub, and not Releaser...

**Comment by AlexWayfer** [comment]
I found the solution: [`fork` parameter](https://developer.github.com/v3/search/#parameters) with `true` value.

Example for my case: https://api.github.com/search/repositories?q=drive+fork:true

@demonspork Your case: https://api.github.com/search/repositories?q=Jackett+fork:true

`true` value for this parameter includes forks and non-forks, so it can be hard-coded (not be UI-option).

Reopen issue, please :cry:

**Comment by tarvip** [comment]
@AlexWayfer thanks, `fork:true` works.

**Comment by Richard87** [comment]
Thanks, I will add it soon!
