### ISSUE TITLE
does not get latest release

### ISSUE THREAD

**Issue by vesper8** [Richard87/releaser#8]
Hi there! First of all thank you for making this! Big kudos! I just got my first notification today from a new release and it's great! Just what I was looking for.

I noticed that one of the 4 projects I am tracking is not showing the latest version on your website https://releaser.richardhagen.no/

It's for https://github.com/mautic/mautic

https://github.com/mautic/mautic/releases shows the latest as being 2.7.1

But on your website it shows 2.7.0

No idea why that is. That's not to say that it wouldn't correctly inform me of a new release.. but wanted to point it out as it seems to be a bug.

Cheers!

**Comment by Richard87** [comment]
Thanks, I will look into it!

Den tor. 20. apr. 2017, 08:28 skrev vesper8 <notifications@github.com>:

**Comment by Richard87** [comment]
Its probably a problem with the atom feed.... I only check once every 30min for a new release, and match the latest release to the previous latest release. If they differ, I send out a notification.

It seems to be working fine for the rest tho, so I'll close this issue :)

**Comment by vesper8** [comment]
thanks. It seems to be all up to date now
